//How do you implement multiple inheritance in Dart
//Ans.Although Dart doesn't support multiple inheritance directly, there are several alternative patterns you can use to simulate similar behavior.
//Mixins. A mixin is a class that provides methods to other classes without being a parent class. ...
//Interfaces. In Dart, you can define an interface using abstract classes. ...
//Composition.
